package rules

import (
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/accessanalyzer"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/apigateway"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/athena"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/cloudfront"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/cloudtrail"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/cloudwatch"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/codebuild"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/config"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/documentdb"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/dynamodb"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/ec2"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/ecr"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/ecs"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/efs"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/eks"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/elasticache"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/elasticsearch"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/elb"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/emr"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/iam"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/kinesis"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/kms"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/lambda"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/mq"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/msk"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/neptune"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/rds"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/redshift"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/s3"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/sam"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/sns"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/sqs"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/ssm"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/aws/workspaces"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/appservice"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/authorization"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/compute"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/container"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/database"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/datafactory"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/datalake"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/keyvault"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/monitor"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/network"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/securitycenter"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/storage"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/azure/synapse"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/cloudstack/compute"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/digitalocean/compute"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/digitalocean/spaces"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/github/actions"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/github/branch_protections"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/github/repositories"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/bigquery"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/compute"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/dns"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/gke"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/iam"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/kms"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/sql"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/google/storage"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/nifcloud/computing"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/nifcloud/dns"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/nifcloud/nas"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/nifcloud/network"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/nifcloud/rdb"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/nifcloud/sslcertificate"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/openstack/compute"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/openstack/networking"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/cloud/oracle/compute"
	_ "github.com/khulnasoft-lab/tunnel-audit/checks/kubernetes/network"
	trules "github.com/khulnasoft-lab/tunnel-audit/pkg/rules"
)

func init() {
	for _, r := range trules.GetRules() {
		Register(r)
	}
}
